// Generated by LiveScript 1.2.0
(function(){
  var truncate;
  truncate = function(text, chars){
    var truncatedText, addEllipsis;
    if (text.length > chars + 1) {
      truncatedText = text.slice(0, chars);
      return addEllipsis = truncatedText + '&hellip;';
    } else {
      return text;
    }
  };
  exports.marked = require('marked');
  exports.moment = require('moment');
  exports.truncate = truncate;
}).call(this);
