// Generated by LiveScript 1.2.0
(function(){
  var routes;
  routes = function(subdirectory, depth){
    var prefix, barePaths, finalPaths, key, value;
    if (depth != null) {
      if (depth === 0) {
        prefix = './';
      } else if (depth === 1) {
        prefix = '../';
      } else if (depth === 2) {
        prefix = '../../';
      } else {
        console.log("depth only goes to 2");
      }
    } else {
      prefix = './';
    }
    barePaths = {
      css: '../assets/css/screen.css',
      about: 'about/',
      all: 'all/',
      categories: 'categories/',
      icons: '../assets/ico/',
      images: '../assets/img/',
      logos: '../assets/img/logos/medium/',
      logosRejected: '../assets/img/logos-rejected/small/',
      projects: 'projects/',
      protocols: 'protocols/',
      'public': '../',
      root: '',
      subcategories: 'subcategories/'
    };
    finalPaths = {};
    for (key in barePaths) {
      value = barePaths[key];
      if (subdirectory === value) {
        if (depth === 2) {
          finalPaths[key] = '../';
        } else {
          finalPaths[key] = '.';
        }
      } else {
        finalPaths[key] = prefix + value;
      }
    }
    return finalPaths;
  };
  exports.routes = routes;
}).call(this);
